// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlM94pf6lA6A_8c8kRkLdOx8hUrD-V-k',
    appId: '1:722731501949:web:0b088037152f18fc6b6414',
    messagingSenderId: '722731501949',
    projectId: 'feellog-74bea',
    authDomain: 'feellog-74bea.firebaseapp.com',
    storageBucket: 'feellog-74bea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIvLliam1Mx_YU8brJunRIzhPp4HKDeU',
    appId: '1:722731501949:android:6a13bc8fd4bdf9a86b6414',
    messagingSenderId: '722731501949',
    projectId: 'feellog-74bea',
    storageBucket: 'feellog-74bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObJhaBoZvHLLNVgAr1yeDIlRtWbMllkQ',
    appId: '1:722731501949:ios:2068250af298093d6b6414',
    messagingSenderId: '722731501949',
    projectId: 'feellog-74bea',
    storageBucket: 'feellog-74bea.firebasestorage.app',
    iosBundleId: 'com.example.feelLog',
  );

}