// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7i0Vh3Cy7u9122K0z2H2qswp-pKMZ5A',
    appId: '1:540800520270:web:97f65ad5e1fc544852f31f',
    messagingSenderId: '540800520270',
    projectId: 'tiktokclone-c9829',
    authDomain: 'tiktokclone-c9829.firebaseapp.com',
    storageBucket: 'tiktokclone-c9829.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBHtGtuyHbcERTEWtvxftuVD1kkm2HK0I',
    appId: '1:540800520270:android:4dcdd5a7136ed9a652f31f',
    messagingSenderId: '540800520270',
    projectId: 'tiktokclone-c9829',
    storageBucket: 'tiktokclone-c9829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOB61rQZ3-BlJbDFLZfgK4-5wRfYSVgU',
    appId: '1:540800520270:ios:9d80c1d79c458ecb52f31f',
    messagingSenderId: '540800520270',
    projectId: 'tiktokclone-c9829',
    storageBucket: 'tiktokclone-c9829.firebasestorage.app',
    iosBundleId: 'com.janice.tiktokClone',
  );

}